name: .NET 8 Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - uses: actions/checkout@v2
      with:
        repository: 'achappey/teams-ai'
        path: 'teams-ai'

    - uses: actions/checkout@v2
      with:
        path: 'teams-aissistant'

    - name: Build Teams-AI Project
      run: dotnet build dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Microsoft.Teams.AI.csproj --configuration Release
      working-directory: teams-ai
 
    - name: Build Teams-Assistant Project
      run: dotnet build --configuration Release
      working-directory: teams-aissistant

    - name: dotnet publish
      run: dotnet publish AIssistant.csproj -c Release -o ./publish
      working-directory: teams-aissistant

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: teams-aissistant
        path: teams-aissistant/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: teams-aissistant
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AzureAppService_bot1Name }} 
          package: ./publish
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a73017872a0e454eb47ee459a6fe629a }}

